# Site/SEO settings
email: brentryanjohnson@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Ryan Johnson
title: Beavercreek Portrait Library
description: >
  Portraits of humans who live or work in Beavercreek, Oregon.
url: 
twitter_username: forestglenroad
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/forestglenroad
  - name: github
    url: https://github.com/rentry

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: 

# MailChimp settings
mailchimp_action: 
mailchimp_input: 

# Author settings
author:
  - name: Ryan Johnson
    bio: Ryan and Erinn live in an old farmhouse in Beavercreek.
    url: http://brentryanjohnson.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Beavercreek Portrait Library'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
